wandb_version: 1

learning_rate:
  desc: null
  value: 0.0005
architecture:
  desc: null
  value: ce
dataset:
  desc: null
  value: cacd
epochs:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684745503.298204
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.9.13
      5: 0.15.3
      8:
      - 3
      - 5
