wandb_version: 1

learning_rate:
  desc: null
  value: 0.0005
architecture:
  desc: null
  value: coral
dataset:
  desc: null
  value: afad
epochs:
  desc: null
  value: 50
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684653875.766595
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.10.9
      5: 0.15.2
      8:
      - 5
